# Generated by Django 4.2.17 on 2024-12-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_monthlyreport_approved_at_alter_monthlyreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hours_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Wykorzystane godziny'),
        ),
    ]
