# Generated by Django 4.2.17 on 2024-12-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_order_number_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='status',
            field=models.CharField(choices=[('active', 'Aktywne'), ('completed', 'Zakończone'), ('archived', 'Zarchiwizowane')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='status',
            field=models.CharField(choices=[('active', 'Aktywne'), ('completed', 'Zakończone'), ('archived', 'Zarchiwizowane')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
