# Generated by Django 4.2.17 on 2024-12-18 18:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_monthlyreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Miesiąc rozliczeniowy')),
                ('total_capex_hours', models.DecimalField(decimal_places=2, default=0, help_text='Suma godzin CAPEX (włącznie z nadgodzinami)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suma godzin CAPEX')),
                ('total_opex_hours', models.DecimalField(decimal_places=2, default=0, help_text='Suma godzin OPEX (włącznie z nadgodzinami)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suma godzin OPEX')),
                ('total_consultation_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suma godzin konsultacji')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Wartość = (suma wszystkich godzin) × stawka godzinowa', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wartość całkowita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='main.order', verbose_name='Zamówienie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Podsumowanie miesięczne',
                'verbose_name_plural': 'Podsumowania miesięczne',
                'ordering': ['-month'],
                'unique_together': {('user', 'month', 'order')},
            },
        ),
    ]
