# Generated by Django 4.2.17 on 2024-12-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_monthlyreportsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capex_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Godziny CAPEX')),
                ('opex_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Godziny OPEX')),
                ('consultation_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Godziny konsultacji')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Wartość całkowita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_value', to='main.order', verbose_name='Zamówienie')),
            ],
            options={
                'verbose_name': 'Wartość zamówienia',
                'verbose_name_plural': 'Wartości zamówień',
            },
        ),
    ]
