# Generated by Django 4.2.17 on 2024-12-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ordervalue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='order',
            name='capex_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budżet CAPEX (h)'),
        ),
        migrations.AddField(
            model_name='order',
            name='consultation_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budżet konsultacji (h)'),
        ),
        migrations.AddField(
            model_name='order',
            name='opex_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budżet OPEX (h)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stawka godzinowa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Numer zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Aktywne'), ('completed', 'Zakończone'), ('canceled', 'Anulowane')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='budget_capex',
        ),
        migrations.RemoveField(
            model_name='order',
            name='budget_consultation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='budget_opex',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='document_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_number',
        ),
    ]
