# Generated by Django 4.2.17 on 2024-12-18 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_unique_together_order_capex_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='orders/attachments/', verbose_name='Załącznik'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data dostawy'),
        ),
        migrations.AddField(
            model_name='order',
            name='document_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data dokumentu'),
        ),
    ]
