# Generated by Django 4.2.17 on 2024-12-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_attachment_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer dostawcy'),
        ),
    ]
