# Generated by Django 4.2.17 on 2024-12-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_order_supplier_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Wersja robocza'), ('active', 'Aktywne'), ('completed', 'Zakończone'), ('canceled', 'Anulowane')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
