# Generated by Django 4.2.17 on 2024-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stawka godzinowa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Wersja robocza'), ('active', 'Aktywne'), ('completed', 'Zakończone'), ('archived', 'Zarchiwizowane')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer dostawy'),
        ),
    ]
